### ISSUE TITLE
devices.json not showing the devices

### ISSUE THREAD

**Issue by DeFesch** [GimpArm/hassio-addons#1]
Hello,
My devices.json file only show me the Smart Friends Box as device and not the rollershutter connected on it.

[
  {
    "Id": 15430,
    "Name": "Smart Friends Box",
    "Room": "LivingRoom",
    "GatewayDevice": "SmartFriendsBox",
    "Manufacturer": "${Manufacturer.SmartHomePartner}",
    "Devices": {}
  }

my config:

SmartFriends:
  Host: 10.20.30.43
  Port: 4300
  Username: *****
  Password: ********
  CSymbol: D19033
  CSymbolAddon: i
  ShcVersion: 2.21.7
  ShApiVersion: '2.20'
Mqtt:
  DataPath: /config/smartfriends2mqtt
  BaseTopic: smartfriends2mqtt
  Server: homeassistant
  Port: 1883
  User: ****
  Password: ****
  UseSsl: false

the log:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
info: SmartFriends.Mqtt.ApplicationService[0]
      StartAsync method called.
info: SmartFriends.Api.Session[0]
      Connecting to 10.20.30.43
info: SmartFriends.Api.Session[0]
      Logging in as Assistent
info: SmartFriends.Api.Session[0]
      Logged in to SmartFriendsBox
info: SmartFriends.Mqtt.MqttClient[0]
      Client Connected to mqtt://homeassistant:1883
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /opt/

Best regards,

**Comment by GimpArm** [comment]
I'm in the process of combining the mqtt with the rest api because there are some things that are just easier to do in the rest api. Only for debugging, can you try setting up the rest api and then going to http://127.0.0.1:5001/raw and post the output?

**Comment by DeFesch** [comment]
Thanks for the fast answer here is the output from the res api 
[raw.txt](https://github.com/GimpArm/hassio-addons/files/6365050/raw.txt)

**Comment by GimpArm** [comment]
So what is very strange, the "master device id" of your shutters is reported as "0", that shouldn't happen, although should still work. Can you try unregistering it on the SmartFriends box and registering it again?

I input your data and it was parsed and would be available as a controllable device. 

With the REST API, do you see your devices at http://127.0.0.1:5001/list ?

**Comment by DeFesch** [comment]
So, I have now done a factory reset on the smart friends box and new registering the shutters. On http://127.0.0.1:5001/list the site is empty and my shutters still have no master device id.
![api list](https://user-images.githubusercontent.com/82998998/116085150-ced45e80-a69e-11eb-9c67-9352b1573301.jpg)

**Comment by GimpArm** [comment]
I don't think this will fix your problem but it will make it easier for me to help you. I released the new add-on which combines both the rest and mqtt called smartfriends-bridge. Please install that, delete the files in your /config/smartfriends2mqtt folder, configure and enable the mqtt section of the config and start the add-on.

Now when it is running do again the http://127.0.0.1:5001/raw and post it to me. Then I think I will be able to figure this out.

**Comment by DeFesch** [comment]
Thank you very much for your work here is the extract from 127.0.0.1/raw
[raw.txt](https://github.com/GimpArm/hassio-addons/files/6383695/raw.txt)

**Comment by GimpArm** [comment]
Ok, that gives me a much clearer picture of what is going on. Rather technical, you can skip to the end if it doesn't interest you. I have no idea why but it looks like you have 2 shutters but they both get assigned to the same master device "0" although they are assigned to different rooms (Living Room & Bed Room). Along with something called a "pushNotificationChain" that I have no idea what that is supposed to do. They were all getting grouped as a single device and since the pushNotificationChain isn't assigned to a room and is marked to be hidden, my system ignores all of them. I made a change that if the MasterDeviceID = 0 then it will treat each sub-device as a stand alone device.

I have updated the system, you should be able to see your devices when you do a /list Just so you know, the devices.json file will no longer be written in the new combined version because the /list will be more up to date anyways.

Now I'm not sure if you're going to gain much from using MQTT because your device does not report position. So it would probably be easier to use REST but if you do want to use MQTT then the default shutter template I provide is not going to work for you. I think something more like this would be appropriate but I'm not sure.

```
{
  "Type": "cover",
  "Class": "shutter",
  "Parameters": {
    "state_stopped": "Stop",
    "state_open": "Up",
    "state_closed": "Down",
    "payload_stop": "Stop",
    "payload_open": "Up",
    "payload_close": "Down"
  }
}
```

**Comment by DeFesch** [comment]
I have now the devices in 127.0.0.1:5001/list an with the api url i can controll the shutters. Thank you for your help
